name: Complete Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [latest]
        compiler: [gfortran]
        comm: [mpiuni]
        netcdf: [nc-config]
        cache: [true]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Package Install (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq -y update
        sudo apt -qq install libnetcdf-dev libnetcdff-dev
    - name: Package Install (macOS)
      if: runner.os == 'macOS'
      run: |
        ln -fs `which gcc-11` /usr/local/bin/gcc
        ln -fs `which g++-11` /usr/local/bin/g++
        ln -fs `which gfortran-11` /usr/local/bin/gfortran
        brew install netcdf netcdf-fortran
    - name: Install ESMF
      uses: ./
      env:
        ESMF_COMPILER: ${{matrix.compiler}}
        ESMF_COMM: ${{matrix.comm}}
        ESMF_NETCDF: ${{matrix.netcdf}}
      with:
        version: ${{matrix.version}}
        cache: ${{matrix.cache}}
    - name: Test ESMF Installation
      run: |
        cat ${ESMFMKFILE}
